apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mongodb-server
    app.kubernetes.io/instance: graylog-mongodb
    app.kubernetes.io/name: graylog-mongodb
  name: graylog-mongodb
  namespace: graylog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb-server
      app.kubernetes.io/instance: graylog-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongodb-server
        app.kubernetes.io/instance: graylog-mongodb
        app.kubernetes.io/name: graylog-mongodb
    spec:
      hostname: graylog-mongodb
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: build-node
                operator: DoesNotExist
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: graylog
              key: graylog.mongodb.user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: graylog.mongodb.password
              name: graylog
        image: mongo:3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 27017
          timeoutSeconds: 1
        name: graylog-mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: graylog-mongodb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: graylog-mongodb-data
        persistentVolumeClaim:
          claimName: graylog-mongodb
