apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: mongodb-server
    app.kubernetes.io/instance: graylog-mongodb
    app.kubernetes.io/name: graylog-mongodb
  name: graylog-mongodb
  namespace: graylog
spec:
  accessModes:
  - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 512Mi
  storageClassName: ""
  volumeName: graylog-mongodb-volume

