apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: mongodb-server
    app.kubernetes.io/instance: graylog-mongodb
    app.kubernetes.io/name: graylog-mongodb
  name: graylog-mongodb
  namespace: graylog
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  storageClassName: default

