apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: graylog
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/name: graylog
  name: graylog
  namespace: graylog
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: graylog
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/name: graylog
  name: graylog
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: graylog
subjects:
- kind: ServiceAccount
  name: graylog
  namespace: graylog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: graylog
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/name: graylog
  name: graylog
  namespace: kube-system
